# Generated by Django 2.2.10 on 2020-03-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200328_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='active',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='cases',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='casesPerOneMillion',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='country_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='critical',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='deaths',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='deathsPerOneMillion',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='loadedDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='recovered',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='todayCases',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='totalDeaths',
            field=models.BigIntegerField(null=True),
        ),
    ]
