# Generated by Django 2.2.10 on 2020-03-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200328_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='country_code',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='country_codeInfo',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='source',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
