# Generated by Django 2.2.10 on 2020-03-28 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200328_0744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['created_at']},
        ),
    ]
